added support for sublimetext (stdin/filename handling)
gforcada/flake8-pep3101 pull request #17
Opened 2017-06-07 07:45 UTC by iham

same problem as with other flake8 packages in sublime ... just forgot to pr ...

2017-06-07 08:18 UTC, gforcada requested changes

2017-06-07 08:18 UTC, gforcada commented on flake8_pep3101.py
> +        if self.filename is 'stdin':
@iham this should be ``self.filename == 'stdin'``, python's ``is`` keyword is for identity check:
```
>>> a = 3
>>> b = 3
>>> a is b
True
>>> id(a)
94616584712504
>>> id(b) 
94616584712504
>>> c = 343434343434344
>>> d = 343434343434344
>>> c is d
False
>>> id(c)
94616585066984
>>> id(d)
94616585067032

2017-06-07 08:18 UTC, gforcada commented on flake8_pep3101.py
> -            lines = pycodestyle.stdin_get_value()
@iham now I'm confused, in all other flake8 plugins the fix for handling stdin input was to use this approach rather that the self.tree as you are doing here, should it be changed everywhere as well? 🤔

2017-06-07 08:20 UTC, gforcada commented
@iham if you want to test for ``stdin`` here is an example test:  https://github.com/gforcada/flake8-builtins/blob/master/run_tests.py#L122-L136

2017-06-07 08:20 UTC, gforcada commented
@iham thanks for all the pull requests!! It is greatly appreciated!! 🙇

2017-06-14 00:06 UTC, gforcada commented
@iham friendly ping 😄

2019-12-15 03:42 UTC, unformatt commented
Is this PR dead? Would love to use this in SublimeText.

2022-10-08 16:18 UTC, gforcada commented
It might be, though I'm not using sublime, that this is already working 🤞🏾 could any of you give a try to the new __2.0.0__ release?

Re-open if it is still not working 😄

2022-10-08 16:18 UTC, closed without merging